
.PHONY: all

all: 
	make -C connect
	make -C execve
	make -C execve_sh
	make -C exit
	make -C helloworld
	make -C readfile
	make -C reusefd

.PHONY: clean

clean:
	make -C connect clean
	make -C execve clean
	make -C execve_sh clean
	make -C exit clean
	make -C helloworld clean
	make -C readfile clean
	make -C reusefd clean